import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

import Navbar from '@/components/Navbar';
import HeaderAuth from '@/components/HeaderAuth';
import Form from '@/components/Form';

const inter = Inter({ weight: ['400', '500', '700'], subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Kudos Lancer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Navbar />
        <HeaderAuth />
      </main>
    </>
  );
}
